/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import uk.ac.kcl.inf.validation.DotLanguageValidator;

/**
 * Custom quickfixes.
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class DotLanguageQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(DotLanguageValidator.MULTIPLE_NODE_DECLARATION_GRAPH)
  public void removeDeclarationGraph(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), "");
    };
    acceptor.accept(issue, "Remove duplicate declaration", 
      "Remove the node declaration which is duplicated in the code. ", null, _function);
  }
  
  @Fix(DotLanguageValidator.MULTIPLE_NODE_DECLARATION_DIGRAPH)
  public void removeDeclarationDigraph(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IModification _function = (IModificationContext context) -> {
      final IXtextDocument xtextDocument = context.getXtextDocument();
      xtextDocument.replace((issue.getOffset()).intValue(), (issue.getLength()).intValue(), "");
    };
    acceptor.accept(issue, "Remove duplicate declaration", 
      "Remove the node declaration which is duplicated in the code. ", null, _function);
  }
}
