/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.dotLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.AttributeList#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getAttributeList()
 * @model
 * @generated
 */
public interface AttributeList extends EObject
{
  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference.
   * @see #setAttributes(Attribute)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getAttributeList_Attributes()
   * @model containment="true"
   * @generated
   */
  Attribute getAttributes();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.AttributeList#getAttributes <em>Attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attributes</em>' containment reference.
   * @see #getAttributes()
   * @generated
   */
  void setAttributes(Attribute value);

} // AttributeList
