/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.dotLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.Attribute#getAttributeName <em>Attribute Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.Attribute#getAttributeValue <em>Attribute Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Name</em>' attribute.
   * @see #setAttributeName(String)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getAttribute_AttributeName()
   * @model
   * @generated
   */
  String getAttributeName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.Attribute#getAttributeName <em>Attribute Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Name</em>' attribute.
   * @see #getAttributeName()
   * @generated
   */
  void setAttributeName(String value);

  /**
   * Returns the value of the '<em><b>Attribute Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute Value</em>' attribute.
   * @see #setAttributeValue(String)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getAttribute_AttributeValue()
   * @model
   * @generated
   */
  String getAttributeValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.Attribute#getAttributeValue <em>Attribute Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute Value</em>' attribute.
   * @see #getAttributeValue()
   * @generated
   */
  void setAttributeValue(String value);

} // Attribute
