/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.dotLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Color Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.ColorAttribute#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getColorAttribute()
 * @model
 * @generated
 */
public interface ColorAttribute extends Attribute
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.dotLanguage.Color}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see uk.ac.kcl.inf.dotLanguage.Color
   * @see #setColor(Color)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getColorAttribute_Color()
   * @model
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.ColorAttribute#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see uk.ac.kcl.inf.dotLanguage.Color
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

} // ColorAttribute
