/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.dotLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directed Subgraph Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.DirectedSubgraphDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.DirectedSubgraphDeclaration#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedSubgraphDeclaration()
 * @model
 * @generated
 */
public interface DirectedSubgraphDeclaration extends DirectedStatement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedSubgraphDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.DirectedSubgraphDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.dotLanguage.DirectedStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedSubgraphDeclaration_Statements()
   * @model containment="true"
   * @generated
   */
  EList<DirectedStatement> getStatements();

} // DirectedSubgraphDeclaration
