/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.dotLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directed Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedStatement()
 * @model
 * @generated
 */
public interface DirectedStatement extends EObject
{
} // DirectedStatement
