/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.dotLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Directed Edge Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.DirectedEdgeDeclaration#getFirstNode <em>First Node</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.DirectedEdgeDeclaration#getEdge <em>Edge</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.DirectedEdgeDeclaration#getSecondNode <em>Second Node</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedEdgeDeclaration()
 * @model
 * @generated
 */
public interface DirectedEdgeDeclaration extends DirectedStatement
{
  /**
   * Returns the value of the '<em><b>First Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Node</em>' reference.
   * @see #setFirstNode(NodeId)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedEdgeDeclaration_FirstNode()
   * @model
   * @generated
   */
  NodeId getFirstNode();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.DirectedEdgeDeclaration#getFirstNode <em>First Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Node</em>' reference.
   * @see #getFirstNode()
   * @generated
   */
  void setFirstNode(NodeId value);

  /**
   * Returns the value of the '<em><b>Edge</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge</em>' attribute.
   * @see #setEdge(String)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedEdgeDeclaration_Edge()
   * @model
   * @generated
   */
  String getEdge();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.DirectedEdgeDeclaration#getEdge <em>Edge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Edge</em>' attribute.
   * @see #getEdge()
   * @generated
   */
  void setEdge(String value);

  /**
   * Returns the value of the '<em><b>Second Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second Node</em>' reference.
   * @see #setSecondNode(NodeId)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getDirectedEdgeDeclaration_SecondNode()
   * @model
   * @generated
   */
  NodeId getSecondNode();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.DirectedEdgeDeclaration#getSecondNode <em>Second Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second Node</em>' reference.
   * @see #getSecondNode()
   * @generated
   */
  void setSecondNode(NodeId value);

} // DirectedEdgeDeclaration
