/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.dotLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.LabelAttribute#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getLabelAttribute()
 * @model
 * @generated
 */
public interface LabelAttribute extends Attribute
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getLabelAttribute_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.LabelAttribute#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

} // LabelAttribute
