/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.dotLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.NodeList#getNodes <em>Nodes</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getNodeList()
 * @model
 * @generated
 */
public interface NodeList extends EObject
{
  /**
   * Returns the value of the '<em><b>Nodes</b></em>' reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.dotLanguage.NodeId}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nodes</em>' reference list.
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getNodeList_Nodes()
   * @model
   * @generated
   */
  EList<NodeId> getNodes();

} // NodeList
