/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.dotLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Right Edge Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.RightEdgeDeclaration#getSecondNode <em>Second Node</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.dotLanguage.RightEdgeDeclaration#getNodeList <em>Node List</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getRightEdgeDeclaration()
 * @model
 * @generated
 */
public interface RightEdgeDeclaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Second Node</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second Node</em>' reference.
   * @see #setSecondNode(NodeId)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getRightEdgeDeclaration_SecondNode()
   * @model
   * @generated
   */
  NodeId getSecondNode();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.RightEdgeDeclaration#getSecondNode <em>Second Node</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second Node</em>' reference.
   * @see #getSecondNode()
   * @generated
   */
  void setSecondNode(NodeId value);

  /**
   * Returns the value of the '<em><b>Node List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node List</em>' containment reference.
   * @see #setNodeList(NodeList)
   * @see uk.ac.kcl.inf.dotLanguage.DotLanguagePackage#getRightEdgeDeclaration_NodeList()
   * @model containment="true"
   * @generated
   */
  NodeList getNodeList();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.dotLanguage.RightEdgeDeclaration#getNodeList <em>Node List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node List</em>' containment reference.
   * @see #getNodeList()
   * @generated
   */
  void setNodeList(NodeList value);

} // RightEdgeDeclaration
