/*
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.dot.ui.internal.DotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DotLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(DotActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		DotActivator activator = DotActivator.getInstance();
		return activator != null ? activator.getInjector(DotActivator.UK_AC_KCL_INF_DOTLANGUAGE) : null;
	}

}
