/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import uk.ac.kcl.inf.services.DotLanguageGrammarAccess;

@SuppressWarnings("all")
public class DotLanguageSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DotLanguageGrammarAccess grammarAccess;
	protected AbstractElementAlias match_DirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q;
	protected AbstractElementAlias match_UndirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DotLanguageGrammarAccess) access;
		match_DirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q = new AlternativeAlias(false, true, new TokenAlias(false, false, grammarAccess.getDirectedStatementAccess().getCommaKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getDirectedStatementAccess().getSemicolonKeyword_1_1()));
		match_UndirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q = new AlternativeAlias(false, true, new TokenAlias(false, false, grammarAccess.getUndirectedStatementAccess().getCommaKeyword_1_0()), new TokenAlias(false, false, grammarAccess.getUndirectedStatementAccess().getSemicolonKeyword_1_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_DirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q.equals(syntax))
				emit_DirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UndirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q.equals(syntax))
				emit_UndirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     (',' | ';')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' '}' (ambiguity) (rule end)
	 *     nodeName=NodeId (ambiguity) (rule end)
	 *     optionalAttributes=AttributeList (ambiguity) (rule end)
	 *     secondNode=[NodeId|ID] (ambiguity) (rule end)
	 *     statements+=DirectedStatement '}' (ambiguity) (rule end)
	 */
	protected void emit_DirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (',' | ';')?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '{' '}' (ambiguity) (rule end)
	 *     nodeName=NodeId (ambiguity) (rule end)
	 *     optionalAttributes=AttributeList (ambiguity) (rule end)
	 *     secondNode=[NodeId|ID] (ambiguity) (rule end)
	 *     statements+=UndirectedStatement '}' (ambiguity) (rule end)
	 */
	protected void emit_UndirectedStatement___CommaKeyword_1_0_or_SemicolonKeyword_1_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
