/**
 * generated by Xtext 2.25.0
 */
package uk.ac.kcl.inf.dotLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.dotLanguage.DotLanguagePackage;
import uk.ac.kcl.inf.dotLanguage.UndirectedStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Undirected Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class UndirectedStatementImpl extends MinimalEObjectImpl.Container implements UndirectedStatement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected UndirectedStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DotLanguagePackage.Literals.UNDIRECTED_STATEMENT;
  }

} //UndirectedStatementImpl
