/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.DotLanguageRuntimeModule;
import uk.ac.kcl.inf.DotLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DotLanguageIdeSetup extends DotLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DotLanguageRuntimeModule(), new DotLanguageIdeModule()));
	}
	
}
