/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.validation;

import org.eclipse.xtext.validation.Check;

import uk.ac.kcl.inf.dotLanguage.DotLanguagePackage;
import uk.ac.kcl.inf.dotLanguage.Graph;


/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class DotLanguageValidator extends AbstractDotLanguageValidator {
	
//	public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					DotLanguagePackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	

// STATIC SEMANTIC CHECKS
	
//	public static DIRECTED_EDGE_IN_GRAPH = 'uk.ac.kcl.inf.dotLanguage.DIRECTED_EDGE_IN_GRAPH'
	/**
	 * Check the graph keyword.
	 */
	
	@Check
	public void checkGraphKeyword(Graph graph) {
		String graphString = graph.toString();
//		if(graphString.substring(0,6) != "graph") {
//			error("");
//		}
		if(graphString.contains("->")){
			error("Graphs must use undirected edge operator --", 
					graph, 
					DotLanguagePackage.Literals.DIRECTED
//					DIRECTED_EDGE_IN_GRAPH
					);
		}
	}
	
	
}
